
export const VIEW_PAGE = 'VIEW_PAGE';
export const FETCH_INTROPAGES_SUCCESS = "FETCH_INTROPAGES_SUCCESS";
export const FETCH_INTROPAGES_FAIL = "FETCH_INTROPAGES_FAIL";

export const SITE_IS_OFFLINE = "SITE_IS_OFFLINE";
export const SITE_IS_ONLINE = "SITE_IS_ONLINE";

export const CONTACT_US_CHANGE_NAME = "CONTACT_US_CHANGE_NAME"
export const CONTACT_US_CHANGE_EMAIL = "CONTACT_US_CHANGE_EMAIL"
export const CONTACT_US_CHANGE_DESC = "CONTACT_US_CHANGE_DESC"
