
export const VIEW_PAGE = 'VIEW_PAGE';
export const FETCH_INTROPAGES = "FETCH_INTROPAGES";
export const FETCH_INTROPAGES_SUCCESS = "FETCH_INTROPAGES_SUCCESS";
export const FETCH_INTROPAGES_FAIL = "FETCH_INTROPAGES_FAIL";


export const CONTACT_US_CHANGE_NAME = "CONTACT_US_CHANGE_NAME"
export const CONTACT_US_CHANGE_EMAIL = "CONTACT_US_CHANGE_EMAIL"
export const CONTACT_US_CHANGE_DESC = "CONTACT_US_CHANGE_DESC"
